package com.example.taskflow.notification;

public enum NotificationEvent {
    TASK_ASSIGNED,
    TASK_SUBMITTED,
    TASK_APPROVED,
    TASK_REJECTED,
    TASK_COMMENTED,
    CHECKLIST_UPDATED,
    TASK_DUE_SOON,
    TASK_OVERDUE,
    TASK_BLOCKED,
    DEPENDENCY_RESOLVED,
    PASSWORD_CHANGED,
    SESSION_REVOKED,
    SYSTEM_MAINTENANCE,
    ACCOUNT_SECURITY_ALERT,
    ORG_INVITE_RECEIVED,
    ORG_INVITE_ACCEPTED,
    ORG_MEMBER_JOINED,
    ORG_MEMBER_LEFT,
    TEAM_MEMBER_ADDED,
    TEAM_MEMBER_REMOVED,
    LEAVE_REQUESTED,
    LEAVE_APPROVED,
    LEAVE_REJECTED
}
