-- Insert all standard permissions into the permissions table if they don't exist.
-- This replaces the hardcoded seed logic in PermissionService.java and OrganizationService.java.

INSERT INTO permissions (name, description)
VALUES 
    ('TASK_VIEW', 'Can view tasks'),
    ('TASK_ASSIGN', 'Can assign tasks'),
    ('TASK_EDIT', 'Can edit tasks'),
    ('TASK_DELETE', 'Can delete tasks'),
    ('TASK_REVIEW', 'Can review tasks'),
    ('TASK_DEPENDENCY_EDIT', 'Can edit task dependencies'),
    ('TASK_REASSIGN', 'Can reassign tasks'),
    ('TASK_ARCHIVE', 'Can archive tasks'),
    ('TASK_OVERRIDE', 'Can override task restrictions'),
    ('ROLE_MANAGE', 'Can manage roles'),
    ('ORG_MEMBER_INVITE', 'Can invite members to organization'),
    ('ORG_MEMBER_REMOVE', 'Can remove members from organization'),
    ('LEAVE_REQUEST_MANAGE', 'Can manage leave requests'),
    ('TEAM_CREATE', 'Can create teams'),
    ('TEAM_MANAGE', 'Can manage teams'),
    ('PROJECT_CREATE', 'Can create projects'),
    ('PROJECT_MANAGE', 'Can manage projects'),
    ('ANNOUNCEMENT_MANAGE', 'Can manage announcements'),
    ('GOAL_MANAGE', 'Can manage goals')
    -- Add new permissions
    ('PERMISSION_MANAGE', 'Can manage permissions'),
    ('PROJECT_ARCHIVE', 'Can archive projects'),
    ('PROJECT_RESTORE', 'Can restore projects'),
    ('PROJECT_EXPORT', 'Can export project data'),
    ('TASK_ARCHIVE_BULK', 'Can bulk archive tasks'),
    ('TASK_REORDER', 'Can reorder tasks'),
    ('TASK_SHARE', 'Can share tasks'),
    ('TASK_TAG_MANAGE', 'Can manage task tags'),
    ('TASK_PIN', 'Can pin tasks'),
    ('ROLE_CREATE', 'Can create roles'),
    ('ROLE_EDIT', 'Can edit roles'),
    ('ROLE_DELETE', 'Can delete roles'),
    ('ORG_MEMBER_EDIT', 'Can edit organization members'),
    ('ORG_MEMBER_VIEW', 'Can view organization members'),
    ('LEAVE_REQUEST_CREATE', 'Can create leave requests'),
    ('LEAVE_REQUEST_APPROVE', 'Can approve leave requests'),
    ('LEAVE_REQUEST_REJECT', 'Can reject leave requests'),
    ('LEAVE_REQUEST_VIEW', 'Can view leave requests'),
    ('LEAVE_BALANCE_MANAGE', 'Can manage leave balances'),
    ('HOLIDAY_MANAGE', 'Can manage holidays'),
    ('TEAM_MEMBER_ADD', 'Can add members to teams'),
    ('TEAM_MEMBER_REMOVE', 'Can remove members from teams'),
    ('TEAM_LEAVE', 'Can manage team leave'),
    ('PROJECT_MEMBER_ADD', 'Can add members to projects'),
    ('PROJECT_MEMBER_REMOVE', 'Can remove members from projects'),
    ('WORK_HOUR_LOG_MANAGE', 'Can manage work hour logs'),
    ('WORK_HOUR_LOG_VIEW', 'Can view work hour logs'),
    ('FILE_MANAGE', 'Can manage files'),
    ('FILE_VIEW', 'Can view files'),
    ('NOTIFICATION_MANAGE', 'Can manage notifications'),
    ('NOTIFICATION_VIEW', 'Can view notifications'),
    ('ACTIVITY_VIEW', 'Can view activities'),
    ('REPORT_VIEW', 'Can view reports'),
    ('WORKSPACE_ACCESS', 'Can access workspace'),
    ('BILLING_MANAGE', 'Can manage billing'),
    ('SETTINGS_MANAGE', 'Can manage settings')
ON CONFLICT (name) DO NOTHING;
